name: Run JUnit Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: Compile Java code
      run: javac -cp .:unittesten/Unittesten/junit-platform-console-standalone-1.9.3.jar:unittesten/Unittesten/src/:unittesten/Unittesten/test/ -d unittesten/bin/main unittesten/Unittesten/src/main/*.java unittestem/Unittesten/test/main/*.java
    - name: Create Jar
      run: jar cf ./unittesten/bin/main/test123.jar -C unittesten/bin/main .

           
    - name: Liste JAR-Inhalte auf
      run: jar tf ./unittesten/bin/main/test123.jar

    - name: Run JUnit Tests
      run: java -jar unittesten/Unittesten/junit-platform-console-standalone-1.9.3.jar --class-path ./unittesten/bin/main/test123.jar --select-package=main
   
