name: Run JUnit Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'liberica'

    #- name: Compile Java code
   #   run: javac unittesten/Unittesten/junit-platform-console-standalone-1.9.3.jar:unittesten/Unittesten/src/main 
   # - name: Create Jar
   #   run: jar cfm test123.jar unittesten/Unittesten/MANIFEST.MF unittesten/Unittesten/bin
   # - name: Run JUnit Tests
   #   run: java -cp .:junit-platform-console-standalone-1.9.3.jar org.junit.runner.JUnitCore
    - name: Compile Java code
      run: javac -cp .:unittesten/Unittesten/junit-platform-console-standalone-1.9.3.jar:unittesten/Unittesten/src/ -d unittesten/Unittesten/bin unittesten/Unittesten/src
    - name: Run JUnit Tests
      
      run: java -cp unittesten/Unittesten/bin:unittesten/junit-platform-console-standalone-1.9.3.jar org.junit.runner.JUnitCore ArtikelTest
#        (your full classpath)                                        (main class)               (your test class)
