name: Run JUnit Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Compile Java code
      run: javac -cp .:unittesten\Unittesten\test\main\ArtikelTest.java
           javac -cp .:unittesten\Unittesten\test\main\MitarbeiterTest.java
           javac -cp .:unittesten\Unittesten\test\main\BestellbestaetigungTest.java
           javac -cp .:unittesten\Unittesten\test\main\BestellpostenTest.java
           javac -cp .:unittesten\Unittesten\test\main\LagerpostenTest.java
           javac -cp .:unittesten\Unittesten\test\main\LagerverwaltungTest.java
    - name: Run JUnit Tests
      run: javac -cp .:unittesten\Unittesten\test\main\ArtikelTest
           javac -cp .:unittesten\Unittesten\test\main\MitarbeiterTest
           javac -cp .:unittesten\Unittesten\test\main\BestellbestaetigungTest
           javac -cp .:unittesten\Unittesten\test\main\BestellpostenTest
           javac -cp .:unittesten\Unittesten\test\main\LagerpostenTest
           javac -cp .:unittesten\Unittesten\test\main\LagerverwaltungTest


